### PR TITLE
fix(executor)!: set_ckb_related_info transaction is not committed

### LINKED ISSUE #1501: Need method to fetch deployment info of `metadata cell` on CKB
context: https://discord.com/channels/674518700518408213/1173534867296895006/1173534872044843039

### PR DESCRIPTION
**Pull request by wenyuanhust**
## What this PR does / why we need it?

This PR will commit if function setCkbRelatedInfo of system contract Metadata is called.

### What is the impact of this PR?

Breaking Change

**PR relation**:
- Ref #

<details><summary>CI Settings</summary><br/>

### **CI Usage**

**Tip**: Check the CI you want to run below, and then comment `/run-ci`.

**CI Switch**

- [ ] Web3 Compatible Tests
- [ ] OCT 1-5 And 12-15
- [ ] OCT 6-10
- [ ] OCT 11
- [ ] OCT 16-19
- [ ] v3 Core Tests

### **CI Description**

| CI Name                                   | Description                                                               |
| ----------------------------------------- | ------------------------------------------------------------------------- |
| *Web3 Compatible Test*                    | Test the Web3 compatibility of Axon                                       |
| *v3 Core Test*                            | Run the compatibility tests provided by Uniswap V3                        |
| *OCT 1-5 \| 6-10 \| 11 \| 12-15 \| 16-19* | Run the compatibility tests provided by OpenZeppelin                      |

</details>

### CODE REVIEW

File: core/executor/src/tests/system_script/metadata.rs [hunk 1]
```diff
@@ -207,6 +208,43 @@ fn prepare_validator() -> ValidatorExtend {
...
+        delegate_smt_type_id: H256::zero(),
+        reward_smt_type_id:   H256::zero(),
+    };
+    let _result = store.set_ckb_related_info(&ckb_infos);
+
+    CURRENT_METADATA_ROOT.with(|root| {
+        let new_root = *root.borrow();
+        println!("new_root: {:?}", new_root);
+        assert_ne!(new_root, metadata_root);
+    });
```
Comment (KaoImin) [inline core/executor/src/tests/system_script/metadata.rs]: The unit test does not cover the changes.

Comment (wenyuanhust) [reply core/executor/src/tests/system_script/metadata.rs]: In unit test, if set_ckb_related_info was executed, then get_ckb_related_info will get the data correctly regardless of the newle added codes (because the data in cache has been update).  
So I just compared the original root and updated root to check.
Any better suggestions?

Comment (KaoImin) [reply core/executor/src/tests/system_script/metadata.rs]: You should check the new root is different from the origin root.

Comment (wenyuanhust) [reply core/executor/src/tests/system_script/metadata.rs]: > You should check the new root is different from the origin root.

Yes, the metadata_root is the origin root.

**Review by KaoImin — APPROVED** [review]

**Review by ashuralyk — APPROVED** [review]
