### PR TITLE
fix: enable estimation mode for query apis

### LINKED ISSUE #1286: Axon returns too low `eth_estimateGas` which is not enough for the transaction execution
### Contact Details

_No response_

### Overview
We're running `v0.1.0-beta.1` on https://testnet.khalani.network.

For some transactions, `eth_estimateGas` returns too low gas estimation, which is not enough to actually execute these transactions.

Example:

```
curl -X POST --location "https://testnet.khalani.network" \
    -H "Content-Type: application/json" \
    -d "{
          \"method\": \"eth_estimateGas\",
          \"params\": [
            {
              \"from\": \"0x78b43E668E24DDAfeE6B1C12D8260E94a2c5f460\",
              \"to\": \"0xcF239718B22E4df02bEA0E138efd7886951A918B\",
              \"data\": \"0x7c39d130000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000005a000000000000000000000000000000000000000000000000000000000000005278266a68aac4a636e7804651a5195885a0da6302f17becfd418ffec744bb0e57700009b57000000000000000000000000cc737a94fecaec165abcf12ded095bb13f037685bc0fd25a7b18e4bd67f9696ca469a83affdb1cb9b5506219e9f9584ec33d5429c840e053c5811532daf83885ebae4eb53cd1fc4b6655d7f7832cbb066839aa0708c0de31bdd0d54b4b731d825af3b07f1d3fbe443f05bbd70abca6c0dc98f6ef21ddb9a356815c3fac1026b6dec5df3124afbadb485c9ba5a3e3398a04b7ba85e2429ef208d3cfb4213bf7cf9961b0c363699771e057a0e9739a526232dbaad50eb01ebfc9ed27500cd4dfc979272d1f0913cc9f66540d7e8005811109e1cf2d3b597dec3d623b9b5f3a052b997e8e156681b03767dcf4de278f5a54bb8f7d3affd70157e48063fc33c97a050f7f640233bf646cc98d9524c6b92bcf3ab56f8399f5e78067575d6fda17129e40c9c205fe8c2cd2af0e8693891bbe77be0439957ea0f82fca1e039bd9b2ee26b965b35ea3ed6e1592871634042764f5e8bff9ddf9dc3e7fe016e050eff260334f18a5d4fe391d82092319f5964f2e2eb7c1c3a590886829e1ef562c741c53b53f7bed8afadb3eb5526718b4294214a47f14ca6795e5e1e9781988fe6558fa40abae054ea061131a5f766ff12bdff2d183ed002ac1df82d9c4b87413eae2ef048f94b4d3554cea73d92b0f7af96e0271c691e2bb5c67add7c6caf302256adedf7ab114da0acfe870d449a3a489f781d659e8beccda7dcc232dbde8951b2eb045a99002d86daf3fbad63d20e4acb802995cc5f2b92733e50f526ec2fa19a22b31e8ed50f23cd1fdf94c9154ed3a7609a2f1ff981fe1d3b5c807b281e4683cc6d6315cf95b9ade8641defcb32372f1c126e398ef7a5a2dce0a8a7f68bb74560f8f71837c2c2ebbcbf7fffb42ae1896f13f7c7479a0b46a28b6f55540f89444f63de0378e3d121be09e06cc9ded1c20e65876d36aa0c65e9645644786b620e2dd2ad648ddfcbf4a7e5b1a3a4ecfe7f64667a3f0b7e2f4418588ed35a2458cffeb39b93d26f18d2ab13bdce6aee58e7b99359ec2dfd95a9c16dc00d6ef18b7933a6f8dc65ccb55667138776f7dea101070dc8796e3774df84f40ae0c8229d0d6069e5c8f39a7c299677a09d367fc7b05e3bc380ee652cdc72595f74c7b1043d0e1ffbab734648c838dfb0527d971b602bc216c9619ef0abf5ac974a1ed57f4050aa510dd9c74f508277b39d7973bb2dfccc5eeb0618db8cd74046ff337f0a7bf2c8e03e10f642c1886798d71806ab1e888d9e5ee87d0838c5655cb21c6cb83313b5a631175dff4963772cce9108188b34ac87c81c41e662ee4dd2dd7b2bc707961b1e646c4047669dcb6584f0d8d770daf5d7e7deb2e388ab20e2573d171a88108e79d820e98f26c0b84aa8b2f4aa4968dbb818ea32293237c50ba75ee485f4c22adf2f741400bdf8d6a9cc7df7ecae576221665d7358448818bb4ae4562849e949e17ac16e0be16688e156b5cf15e098c627c0056a902c79dbff807c62022bd56c41cf82c4e4c5313175de8a86743f110f2b4f22696980e37d136c0b6f04602fa047976983a986236186122e31a27828f72769cf1b5231c881cb6e548f1435cb916f867b6d70aee7c63504d027c734fab38fa5ecb6c8cf1540c211841dbb9307891506c7feee95821a6c29f1aacd560a2a0c2cce5d53cc81b0000000000000000000000009fa19ead5ec76e437948b35e227511b106293c40000000000000000000000000227e7d6507762ece0c94678f8c103eff9d6824760000000000000000000000002379e43740e4aa4fde48cf4f00a3106df1d8420d0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004ed0000009b560000a869000000000000000000000000861867fad95236f256ba318aecd50d814be1dc8f0000271c00000000000000000000000023c1cdd01c95b4ab69c2bdd2a60ab4c63d85af3200000000000000000000000018f814fa6cb21cc51ae0c5594418766f17dfb6a9000000000000000000000000000000000000000000000000000000000000271c00000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000180000000000000000000000000000000000000000000000000000000000000000100000000000000000000000018f814fa6cb21cc51ae0c5594418766f17dfb6a90000000000000000000000000000000000000000000000000000000000000480000000000000000000000000000000000000000000000000000000000000000200000000000000000000000024bcc5d1f6538f4a84cd9009ebd4fa614904fa5900000000000000000000000000000000000000000000000000000000000f4240000000000000000000000000df830a3f120515bd99fe6bc8513537713e204bc500000000000000000000000000000000000000000000000000000000000f424000000000000000000000000000000000000000000000000000000000000002c4642182f300000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000001c000000000000000000000000000000000000000000000000000000000000002400000000000000000000000000000000000000000000000000000000064c39d9b0000000000000000000000000000000000000000000000000000000000000100bdb2ade29dd506c115b6afc761862e2070e966fe000000000000000000000006000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000de0b6b3a7640000bdb2ade29dd506c115b6afc761862e2070e966fe000000000000000000000006000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000de0b6b3a76400000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000875863d88bf0c9a088a274a0263a903434b306aa000000000000000000000000bdb2ade29dd506c115b6afc761862e2070e966fe000000000000000000000000dc28d2d648ed4c4c6fb641a46e9f4d73ae236de100000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\",
              \"gas\": \"0xffffff\"
            },
            \"latest\"
          ],
          \"id\": 48,
          \"jsonrpc\": \"2.0\"
        }"
```

returns
```
{
  "jsonrpc": "2.0",
  "result": "0xc750c",
  "id": 48
}
```

if we try to `eth_call` with `0xc750c` gas:
```
curl -X POST --location "https://testnet.khalani.network" \
    -H "Content-Type: application/json" \
    -d "{
          \"method\": \"eth_call\",
          \"params\": [
            {
              \"from\": \"0x78b43E668E24DDAfeE6B1C12D8260E94a2c5f460\",
              \"to\": \"0xcF239718B22E4df02bEA0E138efd7886951A918B\",
              \"data\": \"0x7c39d130000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000005a000000000000000000000000000000000000000000000000000000000000005278266a68aac4a636e7804651a5195885a0da6302f17becfd418ffec744bb0e57700009b57000000000000000000000000cc737a94fecaec165abcf12ded095bb13f037685bc0fd25a7b18e4bd67f9696ca469a83affdb1cb9b5506219e9f9584ec33d5429c840e053c5811532daf83885ebae4eb53cd1fc4b6655d7f7832cbb066839aa0708c0de31bdd0d54b4b731d825af3b07f1d3fbe443f05bbd70abca6c0dc98f6ef21ddb9a356815c3fac1026b6dec5df3124afbadb485c9ba5a3e3398a04b7ba85e2429ef208d3cfb4213bf7cf9961b0c363699771e057a0e9739a526232dbaad50eb01ebfc9ed27500cd4dfc979272d1f0913cc9f66540d7e8005811109e1cf2d3b597dec3d623b9b5f3a052b997e8e156681b03767dcf4de278f5a54bb8f7d3affd70157e48063fc33c97a050f7f640233bf646cc98d9524c6b92bcf3ab56f8399f5e78067575d6fda17129e40c9c205fe8c2cd2af0e8693891bbe77be0439957ea0f82fca1e039bd9b2ee26b965b35ea3ed6e1592871634042764f5e8bff9ddf9dc3e7fe016e050eff260334f18a5d4fe391d82092319f5964f2e2eb7c1c3a590886829e1ef562c741c53b53f7bed8afadb3eb5526718b4294214a47f14ca6795e5e1e9781988fe6558fa40abae054ea061131a5f766ff12bdff2d183ed002ac1df82d9c4b87413eae2ef048f94b4d3554cea73d92b0f7af96e0271c691e2bb5c67add7c6caf302256adedf7ab114da0acfe870d449a3a489f781d659e8beccda7dcc232dbde8951b2eb045a99002d86daf3fbad63d20e4acb802995cc5f2b92733e50f526ec2fa19a22b31e8ed50f23cd1fdf94c9154ed3a7609a2f1ff981fe1d3b5c807b281e4683cc6d6315cf95b9ade8641defcb32372f1c126e398ef7a5a2dce0a8a7f68bb74560f8f71837c2c2ebbcbf7fffb42ae1896f13f7c7479a0b46a28b6f55540f89444f63de0378e3d121be09e06cc9ded1c20e65876d36aa0c65e9645644786b620e2dd2ad648ddfcbf4a7e5b1a3a4ecfe7f64667a3f0b7e2f4418588ed35a2458cffeb39b93d26f18d2ab13bdce6aee58e7b99359ec2dfd95a9c16dc00d6ef18b7933a6f8dc65ccb55667138776f7dea101070dc8796e3774df84f40ae0c8229d0d6069e5c8f39a7c299677a09d367fc7b05e3bc380ee652cdc72595f74c7b1043d0e1ffbab734648c838dfb0527d971b602bc216c9619ef0abf5ac974a1ed57f4050aa510dd9c74f508277b39d7973bb2dfccc5eeb0618db8cd74046ff337f0a7bf2c8e03e10f642c1886798d71806ab1e888d9e5ee87d0838c5655cb21c6cb83313b5a631175dff4963772cce9108188b34ac87c81c41e662ee4dd2dd7b2bc707961b1e646c4047669dcb6584f0d8d770daf5d7e7deb2e388ab20e2573d171a88108e79d820e98f26c0b84aa8b2f4aa4968dbb818ea32293237c50ba75ee485f4c22adf2f741400bdf8d6a9cc7df7ecae576221665d7358448818bb4ae4562849e949e17ac16e0be16688e156b5cf15e098c627c0056a902c79dbff807c62022bd56c41cf82c4e4c5313175de8a86743f110f2b4f22696980e37d136c0b6f04602fa047976983a986236186122e31a27828f72769cf1b5231c881cb6e548f1435cb916f867b6d70aee7c63504d027c734fab38fa5ecb6c8cf1540c211841dbb9307891506c7feee95821a6c29f1aacd560a2a0c2cce5d53cc81b0000000000000000000000009fa19ead5ec76e437948b35e227511b106293c40000000000000000000000000227e7d6507762ece0c94678f8c103eff9d6824760000000000000000000000002379e43740e4aa4fde48cf4f00a3106df1d8420d0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004ed0000009b560000a869000000000000000000000000861867fad95236f256ba318aecd50d814be1dc8f0000271c00000000000000000000000023c1cdd01c95b4ab69c2bdd2a60ab4c63d85af3200000000000000000000000018f814fa6cb21cc51ae0c5594418766f17dfb6a9000000000000000000000000000000000000000000000000000000000000271c00000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000180000000000000000000000000000000000000000000000000000000000000000100000000000000000000000018f814fa6cb21cc51ae0c5594418766f17dfb6a90000000000000000000000000000000000000000000000000000000000000480000000000000000000000000000000000000000000000000000000000000000200000000000000000000000024bcc5d1f6538f4a84cd9009ebd4fa614904fa5900000000000000000000000000000000000000000000000000000000000f4240000000000000000000000000df830a3f120515bd99fe6bc8513537713e204bc500000000000000000000000000000000000000000000000000000000000f424000000000000000000000000000000000000000000000000000000000000002c4642182f300000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000001c000000000000000000000000000000000000000000000000000000000000002400000000000000000000000000000000000000000000000000000000064c39d9b0000000000000000000000000000000000000000000000000000000000000100bdb2ade29dd506c115b6afc761862e2070e966fe000000000000000000000006000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000de0b6b3a7640000bdb2ade29dd506c115b6afc761862e2070e966fe000000000000000000000006000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000de0b6b3a76400000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000875863d88bf0c9a088a274a0263a903434b306aa000000000000000000000000bdb2ade29dd506c115b6afc761862e2070e966fe000000000000000000000000dc28d2d648ed4c4c6fb641a46e9f4d73ae236de100000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\",
              \"gas\": \"0xc750c\"
            },
            \"latest\"
          ],
          \"id\": 48,
          \"jsonrpc\": \"2.0\"
        }"
```

that transaction will revert:
```
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32015,
    "message": "execution reverted: '­]",
    "data": "0x27ad845d"
  },
  "id": 48
}
```

increasing the estimation by 10k/50k does not help.
`0xc750c` is 816396. Only making the gas 1M (`0xF4240`) works.

### Expected Behavior

Expected Behavior:

### OS

Ubuntu

### Axon version

v0.1.0-beta.1

### Kernel

Ubuntu

### Relevant log output

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chaoticlonghair**
## What this PR does / why we need it?

This PR may resolves #1286.

Ref:
- [EIP-150: Gas cost changes for IO-heavy operations](https://eips.ethereum.org/EIPS/eip-150) (see "all but one 64th" part).
- [EIP-2929: Gas cost increases for state access opcodes](https://eips.ethereum.org/EIPS/eip-2929)

### What is the impact of this PR?

No Breaking Change

<details><summary>CI Settings</summary><br/>

### **CI Usage**

**Tip**: Check the CI you want to run below, and then comment `/run-ci`.

**CI Switch**

- [x] Web3 Compatible Tests
- [x] OCT 1-5 And 12-15
- [x] OCT 6-10
- [x] OCT 11
- [x] OCT 16-19
- [x] v3 Core Tests

### **CI Description**

| CI Name                                   | Description                                                               |
| ----------------------------------------- | ------------------------------------------------------------------------- |
| *Web3 Compatible Test*                    | Test the Web3 compatibility of Axon                                       |
| *v3 Core Test*                            | Run the compatibility tests provided by Uniswap V3                        |
| *OCT 1-5 \| 6-10 \| 11 \| 12-15 \| 16-19* | Run the compatibility tests provided by OpenZeppelin                      |

</details>

_p.s. This PR is created via [GitHub CLI](https://cli.github.com/ "Try it!")._

### CODE REVIEW

**Comment by chaoticlonghair** [comment]
/run-ci

_p.s. This comment is created via [GitHub CLI](https://cli.github.com/ "Try it!")._

**Review by KaoImin — DISMISSED** [review]

File: core/executor/src/lib.rs [hunk 1]
```diff
@@ -73,7 +73,11 @@ impl Executor for AxonExecutor {
         data: Vec<u8>,
     ) -> TxResp {
         self.init_local_system_contract_roots(backend);
-        let config = self.config();
+        let config = {
+            let mut config = self.config();
+            config.estimate = true;
```
Comment (Flouse) [inline core/executor/src/lib.rs:79]:
```suggestion
            // run the gasometer in estimate mode
            config.estimate = true;
```

**Review by Flouse — DISMISSED** [review]

**Review by Flouse — APPROVED** [review]
