### PR TITLE
fix(consensus): correct receipts root

### LINKED ISSUE #1258: The implemention of receipts root in block is incorrect
### Contact Details

_No response_

#### Summary

If "Axon is compatible with Ethereum" as that written in the [README.md](https://github.com/axonweb3/axon/tree/c7a471b#developer-friendly-design), the implementation of receipts root in block is incorrect.

#### Details

- The `Block::receipts_root` is set from `ExecResp.receipt_root`.

  https://github.com/axonweb3/axon/blob/c7a471b596e9dd62c5964ef796d9c41a7b4c17b6/protocol/src/types/block.rs#L118

- The `ExecResp.receipt_root` is merkle root of a list of `hashes`.

  https://github.com/axonweb3/axon/blob/c7a471b596e9dd62c5964ef796d9c41a7b4c17b6/core/executor/src/lib.rs#L175-L182

- Each `hash` in `hashes` is `AxonExecutor::evm_exec(...).ret`.

  https://github.com/axonweb3/axon/blob/c7a471b596e9dd62c5964ef796d9c41a7b4c17b6/core/executor/src/lib.rs#L142-L149

- `TxResp.ret` is set from `res`.

   https://github.com/axonweb3/axon/blob/c7a471b596e9dd62c5964ef796d9c41a7b4c17b6/core/executor/src/lib.rs#L282-L284

- The `res` is `transact_call(...).1`

  https://github.com/axonweb3/axon/blob/c7a471b596e9dd62c5964ef796d9c41a7b4c17b6/core/executor/src/lib.rs#L232-L248

- So, the `res` is just [`Vec<u8>` which represents the return data of the called contract](https://github.com/rust-blockchain/evm/blob/6274e6dd2d43ea84a52573f871fe62047d314e22/src/executor/stack/executor.rs#L515-L523), it is NOT the receipt of transaction.

### Expected Behavior

None.

### OS

Not Associated

### Axon version

_No response_

### Kernel

Not Associated

### Relevant log output

_No response_

### Anything else?

p.s. I don't like your issue template, at least it's not suitable for this issue.

### LINKED ISSUE #1260: Receipts should support `EIP-2718`  since Tansactions already support `EIP-2930` and `EIP-1559`
### Contact Details

_No response_

#### Summary

In EIPs, it said:
- [`EIP-2930`] requires [`EIP-2718`], `EIP-2929`.
- [`EIP-1559`] requires [`EIP-2718`], [`EIP-2930`].

Axon transactions support [`EIP-2930`] and [`EIP-1559`]:

https://github.com/axonweb3/axon/blob/c7a471b596e9dd62c5964ef796d9c41a7b4c17b6/protocol/src/types/transaction.rs#L21-L25

But Axon receipts not support [`EIP-2718`].

#### Details

According to [`EIP-2718`]:

> `Receipt` is either `TransactionType || ReceiptPayload` or `LegacyReceipt`.
> ... ...
> `LegacyReceipt` is kept to be RLP encoded bytes; it is `rlp([status, cumulativeGasUsed, logsBloom, logs])`.
> ... ...
> `ReceiptPayload` is an opaque byte array whose interpretation is dependent on the `TransactionType` and defined in future EIPs.

As [`EIP-2930`] defined: if `TransactionType` is `1`, `ReceiptPayload` is `rlp([status, cumulativeGasUsed, logsBloom, logs])`.

As [`EIP-1559`] defined: if `TransactionType` is `2`, `ReceiptPayload` is `rlp([status, cumulative_transaction_gas_used, logs_bloom, logs])`.

[`EIP-2718`]: https://eips.ethereum.org/EIPS/eip-2718#receipts
[`EIP-2930`]: https://eips.ethereum.org/EIPS/eip-2930#parameters
[`EIP-1559`]: https://eips.ethereum.org/EIPS/eip-1559#specification

### Alternatives you've considered

_No response_

### Anything else?

It's almost impossible to verify a Axon receipt with receipts root:
- Axon receipts not support `EIP-2718`.
- Without `EIP-2718`, the RLP-serialised `LegacyReceipt` also is incorrect (ref: #1259).
- Even users use the Axon-specific RLP-serialised of receipts, the `receipts_root` is still could be verified since the incorrect `LegacyReceipt` is not used when calculates `receipts_root` (ref: #1258).

### PR DESCRIPTION
**Pull request by chaoticlonghair**
**What this PR does / why we need it**:

This PR will fix the incorrect receipts root.

**Which issue(s) this PR fixes**:

- Fixes #1258 
- Fixes #1260

**Which toolchain this PR adaption**:

Breaking Change:
- Receipts root for all blocks are changed.

**Special notes for your reviewer**:

This PR should be released with the `migrate` sub-command together, which will push request later.

**CI Description**

| CI Name                                   | Description                                                     |
| ----------------------------------------- | --------------------------------------------------------------- |
| *Chaos CI*                                | Test the liveness and robustness of Axon under terrible network condition    |
| *Cargo Clippy*                            | Run `cargo clippy --all --all-targets --all-features`      |
| *Coverage Test*                           | Get the unit test coverage report                             |
| *E2E Test*                                | Run end-to-end test to check interfaces                         |
| *Code Format*                             | Run `cargo +nightly fmt --all -- --check` and `cargo sort -gwc`     |
| *Web3 Compatible Test*                    | Test the Web3 compatibility of Axon                               |
| *v3 Core Test*                            | Run the compatibility tests provided by Uniswap V3             |
| *OCT 1-5 \| 6-10 \| 11 \| 12-15 \| 16-19* | Run the compatibility tests provided by OpenZeppelin           |

**CI Usage**

> Check the CI you want to run below, and then comment `/run-ci`.

**CI Switch**

- [x] Chaos CI
- [x] Cargo Clippy
- [ ] Coverage Test
- [x] E2E Tests
- [x] Code Format
- [x] Unit Tests
- [x] Web3 Compatible Tests
- [ ] OCT 1-5 And 12-15
- [ ] OCT 6-10
- [ ] OCT 11
- [ ] OCT 16-19
- [ ] v3 Core Tests

### CODE REVIEW

File: core/executor/src/lib.rs [hunk 1]
```diff
@@ -354,7 +357,10 @@ impl AxonExecutor {
             gas += r.gas_used;
             fee = fee.checked_add(r.fee_cost).unwrap_or(U256::max_value());
 
-            hashes.push(Hasher::digest(&r.ret));
+            let logs_bloom = logs_bloom(r.logs.iter());
+            let receipt = tx.encode_receipt(&r, logs_bloom);
+
+            hashes.push(Hasher::digest(&receipt));
```
Comment (KaoImin) [inline core/executor/src/lib.rs:363]: The `hashes` should be renamed as `receipts`.

Comment (chaoticlonghair) [reply core/executor/src/lib.rs:363]: > The `hashes` should be renamed as `receipts`.

I think the name is correct, since it's a vector of receipt hashes.

The only thing which make me uncomfortable is that I didn't find a test vector to prove my code is correct.

**Review by KaoImin — APPROVED** [review]

**Review by Flouse — APPROVED** [review]
